<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DocuMind.Tests" />
  </ItemGroup>

</Project>
